services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python3 main.py"
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    restart: unless-stopped

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    command: >
      sh -c "python3 main.py"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
