global:
  scrape_interval: 5s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['host.docker.internal:8000']  # FastAPI, если он работает локально
