services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: donalds-back
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080" ]
    restart: unless-stopped
    volumes:
      - ./app/storage/:/app/storage/
      - ./app/settings.json:/app/settings.json
      - ./app/.env:/app/.env
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - wp_network
#    depends_on:
#      db:
#        condition: service_healthy


#include:
#  - ./database/db-compose.yaml
#  - ./vault/vault-compose.yaml