services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - "8300:8300"
    cap_add:
      - IPC_LOCK
#    environment:
#      VAULT_ADDR: "http://0.0.0.0:8200"
    command: "server -config=/vault/config/vault.hcl"
    volumes:
      - ./vault_data:/vault/file
      - ./config:/vault/config
      - ./logs:/vault/logs
