"""wallet_version added

Revision ID: 36b0f5fb89c0
Revises: a820e7d5196f
Create Date: 2025-01-22 00:46:08.407568

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from settings import settings

# revision identifiers, used by Alembic.
revision: str = '36b0f5fb89c0'
down_revision: Union[str, None] = 'a820e7d5196f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create type appwalletversion as enum ('V4R2', 'V5R1');")
    op.execute(f"alter type appwalletversion owner to {settings.db.user};")
    op.add_column('app_wallets',
                  sa.Column('wallet_version', sa.Enum('V4R2', 'V5R1', name='appwalletversion'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_wallets', 'wallet_version')
    op.execute("""drop type appwalletversion;""")
    # ### end Alembic commands ###
