"""add reward and accuracy

Revision ID: 7527d0d58d5e
Revises: fe42a597af87
Create Date: 2025-02-13 22:04:26.517922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7527d0d58d5e'
down_revision: Union[str, None] = 'fe42a597af87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap')
    op.add_column('bets', sa.Column('reward', sa.Float(), nullable=True))
    op.add_column('bets', sa.Column('accuracy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bets', 'accuracy')
    op.drop_column('bets', 'reward')
    op.create_table('swap',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('block_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], name='swap_block_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='swap_pkey')
    )
    # ### end Alembic commands ###
