"""fk bet-block

Revision ID: b0dcb9992a5b
Revises: 151260fde6cd
Create Date: 2024-12-26 14:54:28.394891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0dcb9992a5b'
down_revision: Union[str, None] = '151260fde6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('block_id', sa.UUID(), nullable=False))
    op.drop_index('ix_bets_block_number', table_name='bets')
    op.create_index(op.f('ix_bets_block_id'), 'bets', ['block_id'], unique=False)
    op.create_foreign_key(None, 'bets', 'blocks', ['block_id'], ['id'])
    op.drop_column('bets', 'block_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('block_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bets', type_='foreignkey')
    op.drop_index(op.f('ix_bets_block_id'), table_name='bets')
    op.create_index('ix_bets_block_number', 'bets', ['block_number'], unique=False)
    op.drop_column('bets', 'block_id')
    # ### end Alembic commands ###
