"""optional tg_id

Revision ID: cf7218aef951
Revises: cd9c98f84d5b
Create Date: 2024-12-28 00:07:59.615356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7218aef951'
down_revision: Union[str, None] = 'cd9c98f84d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chains', 'pairs', ['pair_id'], ['id'])
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'chains', type_='foreignkey')
    # ### end Alembic commands ###
