services:
  db:
    image: postgres:17
    container_name: donalds-db
    restart: unless-stopped
    volumes:
      - donalds_pgdata:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "5431:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  donalds_pgdata: